hordii-rushynets/TEP-Backend

backend/settings.py
store/views.py

Add filter of product variants by product ID

Feature filter product variants

---

store/filters.py

Promotion filter

---

cart/models.py
store/filters.py
store/serializers.py
store/views.py

[THT-85] - Add an endpoint for returning popular products

[THT-85] - Add an endpoint for returning popular products

---

store/admin.py
store/models.py
store/serializers.py
store/translation.py

[THT-91] Dimensional grid

---

store/views.py

[THT-88] -  Add endpoint to delete all favourite products

[THT-88] -  Add endpoint to delete all favourite products

---

backend/settings.py
tep_user/admin.py
tep_user/models.py
tep_user/serializers.py
tep_user/urls.py
tep_user/views.py

[THT-61] - add endpoints to partial update of user profile data.

[THT-61] - add endpoints to partial update of user profile data.

---

backend/settings.py

[THT-94] - Add Russian language to backend

[THT-94] - Add Russian language to backend

---

.gitignore
vacancy/admin.py
vacancy/models.py
vacancy/serializers.py
vacancy/urls.py
vacancy/views.py

[THT-128] - Response to a vacancy

[THT-128] - Response to a vacancy

---

backend/settings.py
store/serializers.py

[THT-103] - Add checkbox “added to cart” for product by specific user

[THT-103] - Add checkbox “added to cart” for product by specific user

---

blog/pagination.py
blog/views.py

[THT-124] - Add pagination to BlogPostViewSet

[THT-124] - Add pagination to BlogPostViewSett

---

tep_user/models.py
tep_user/serializers.py
tep_user/urls.py
tep_user/views.py

[THT-133] -  Add an address to a user model

[THT-133] -  Add an address to a user model

---

cart/models.py

[THT-134] - Fixed bug in cart

---

store/admin.py
store/models.py
store/serializers.py
store/urls.py
store/views.py

[THT-136] - Add model for inspiration images

[THT-136] - Add model for inspiration images

---

blog/serializers.py
store/serializers.py

[THT-94] -  Add Russian language to backend

[THT-94] -  Add Russian language to backend

---

blog/serializers.py

[THT-168] - Bugfix in SectionSerializer

[THT-168] - Bugfix in SectionSerializer 

---

store/admin.py
store/models.py
tep_user/admin.py

Fixed:
Rename fields in store/admin.py in "Product photo in interior"
Add fields to list_display in TEPUserAdmin

Bugfix admin 

---

blog/admin.py
blog/models.py
blog/serializers.py
blog/translation.py

Added: photo and description to materials

---

cart/models.py
cart/serializers.py
cart/views.py
post/models.py
post/services/abstract_delivery_service.py
post/views.py
store/serializers.py
store/views.py
tep_user/authentication.py

[BHT-12] - Fix in_cart. Attach product from cart to product variant

[BHT-12] - Fix in_cart. Attach product from cart to product variant

---

store/views.py

[TP2-24] - Correction of errors in the recommended

[TP2-24] - Correction of errors in the recommended 

---

post/services/abstract_delivery_service.py

[TP2-35] - Fix saving filter fields

[TP2-35] - Fix saving filter fields

---

post/views.py

[TP2-43] - Show history of orders by IP

[TP2-43] - Show history of orders by IP

---

store/serializers.py
store/urls.py
store/views.py

[TP2-42] - Add endpoint that returns all sizes, materials and colors of all products of the certain category

[TP2-42] - Add endpoint that returns all sizes, materials and colors of all products of the certain category

---

store/admin.py
store/models.py
store/translation.py

[TP2-47] - Add new field with description of the product in product model that will be shown in dymensional grid

[TP2-47] - Add new field with description of the product in product model that will be shown in dymensional grid

---

store/admin.py
store/models.py
store/serializers.py

[TP2-26] Search by SKU or Group ID in product variant (admin). Show Group ID and SKU in list_display
FIXED: 500 error when retrieving products
FIXED: only one color in product variant

[TP2-26] Search by SKU or Group ID in product variant (admin). Show Group ID and SKU in list_display

---

backend/middleware.py
backend/settings.py
blog/serializers.py

[TP2-40] - add logging

---

backend/settings.py
cart/views.py
store/admin.py
store/models.py
store/serializers.py
store/until.py
store/views.py

[TP2-52] - Favorites tab for unregistered users

[TP2-52] - Favorites tab for unregistered users

---

cart/views.py
store/pagination.py
store/serializers.py
store/views.py

[TP2-57] - add pagiantion to products

[TP2-57] - add pagiantion to products
